version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  express-api:
    build:
      context: ./api
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "5000:5000"

volumes:
  postgres-db:
# docker-compose run express-api npm run migrate (run migrations within container to build image, create persistent data volume and create table)
# docker-compose up
