version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - learningnode-db:/var/lib/postgresql/data

  learningnode:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  learningnode-db:
# docker-compose run addressbook npm run migrate (run migrations within container to build image, create persistent data volume and create table)
# docker-compose up
